public class CreateService7FeedbackQueueable implements Queueable, Database.AllowsCallouts {
    

    // NOT IN USE //

    // private List<Service_7_Sample_Feedbacks__c> records;

    // public CreateService7FeedbackQueueable(List<Service_7_Sample_Feedbacks__c> records) {
    //     this.records = records;
    // }

    public void execute(QueueableContext context) {
    //     for (Service_7_Sample_Feedbacks__c rec : records) {
    //         createService7SamplefeedbackTrigHandler.updateSentAPICallout(rec.InvoiceNo__c);
    //     }
    }

}