public class customerWC {
    public String No; // Customer_Code__c
    public String Name; // Name
    public String Address; // BillingStreet
    public String Address_2; // ShippingStreet
    public String City; // BillingCity
    public String Country_Region_Code; //Country_Region_Code__c
    public String Phone_No; // Phone
    public String Credit_Limit_LCY; // Credit_Limit_Requested__c
    public String Customer_Posting_Group; // Customer_Posting_Group__c
    public String Customer_Price_Group; // Customer_Price_Group__c
    public String Payment_Terms_Code; // Payment_Terms_Code__c
    public String Blocked; // Blocked__c
    public String Last_Date_Modified; // aaa
    public String Gen_Bus_Posting_Group; // Gen_Bus_Posting_Group__c
    public String Post_Code; // BillingPostalCode
    public String P_A_N_No; // P_A_N_No__c
    public String State_Code; // State_Code__c
    public String GST_Registration_No; // GST_Registration_No__c
    public String GST_Registration_Type; // GST_Registration_Type__c
    public String GST_Customer_Type; // GST_Customer_Type__c
    public String Customer_Type; // Customer_Type__c
    public String Turnover; // Turnover__c
    public String ITR_Status; // ITR_Status__c
    public String Whatsapp_Mobile_No; //Whatsapp_Mobile_No__c
    public String SalesOrderDetailEmail; // SalesOrderDetailEmail__c
    public String Creation_Date; // aaa
    public String Ofline_Order; // Ofline_Order__c
    public String Exclude_from_Loyalty_program; // Exclude_from_Loyalty_program__c
    public String DF_Finance_Customer; // DF_Financial_Customer__c
    public String DF_Finance_Customer_No; // DF_Financial_Customer_No__c

}